/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <android/log.h>
/* Header for class com_example_hellojni_util_NumberUtil */

#ifndef _Included_com_example_hellojni_util_NumberUtil
#define _Included_com_example_hellojni_util_NumberUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_util_NumberUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_hellojni_util_NumberUtil_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_hellojni_util_NumberUtil
 * Method:    getNumbers
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_hellojni_util_NumberUtil_getNumbers
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
