/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_example_hellojni_util_StringUtil */

#ifndef _Included_com_example_hellojni_util_StringUtil
#define _Included_com_example_hellojni_util_StringUtil
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_hellojni_util_StringUtil
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hellojni_util_StringUtil_init
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hellojni_util_StringUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_util_StringUtil_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_example_hellojni_util_StringUtil
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_util_StringUtil_getString__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
